name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]
    tags: ['*']

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Build and Test
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      # define Java options for both official sbt and sbt-extras
      JAVA_OPTS: -Dfile.encoding=UTF-8
      JVM_OPTS:  -Dfile.encoding=UTF-8
    steps:
      - uses: actions/checkout@v3
      - name: Set up JVM
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'sbt'
      - run: sbt -v clean test scripted
      - name: Scalafmt
        shell: bash
        run: sbt -v clean scalafmtSbtCheck scalafmtCheckAll
